### ISSUE TITLE
Layer 3 Firewall rules

### ISSUE THREAD

**Issue by Beardwin1** [CiscoDevNet/ansible-meraki#300] opened 2022-04-07 05:09 UTC
Hi,

I'm not sure if it was developed in this manner but I seem to have spotted an issue. When running the below play: 

![image](https://user-images.githubusercontent.com/86856010/162124254-67dbe5c5-6855-49b3-8608-f34b07de8863.png)

After running the playbook, if there are any firewall rules that have been created, this will delete them all and replace them with just the 1 firewall rule specified in the play. Is there a way we can "add" rather than "set" firewall rules?

Documentation found below:
https://docs.ansible.com/ansible/latest/collections/cisco/meraki/meraki_mx_l3_firewall_module.html#ansible-collections-cisco-meraki-meraki-mx-l3-firewall-module

**Comment by kbreit** [comment] 2022-04-07 06:57
This is how it works by design. It's how the API works and to modify this would be a rewrite of the module and would break backward compatibility. The first note for the module states

> Module assumes a complete list of firewall rules are passed as a parameter.

What are you trying to do?

**Comment by Beardwin1** [comment] 2022-04-07 14:35
> This is how it works by design. It's how the API works and to modify this would be a rewrite of the module and would break backward compatibility. The first note for the module states
> 
> > Module assumes a complete list of firewall rules are passed as a parameter.
> 
> What are you trying to do?

So it's not ideal to use it for adding extra firewall rules if there are existing firewall rules already?

**Comment by kbreit** [comment] 2022-04-08 01:21
Correct. It wants to own all the rules.

Do you have experience with Python? If so you may want to look into writing an Ansible filter to manipulate the rules.

**Comment by Beardwin1** [comment] 2022-04-08 03:05
> Correct. It wants to own all the rules.
> 
> Do you have experience with Python? If so you may want to look into writing an Ansible filter to manipulate the rules.

Not the best still doing some studies on Python, do you have any documentation to point me to at all? But that's fine thanks a lot for the help and advice!

**Comment by kbreit** [comment] 2022-05-11 21:56
@Beardwin1 Sorry I am just now getting back to you. I have an example for something else I did. See https://github.com/kbreit/ansible-demos/tree/main/6-port_config_filter for an example.

**Comment by kbreit** [comment] 2022-05-11 21:57
I am going to close this for now but happy to continue the discussion.

**Closed by kbreit** 2022-05-11 21:57 UTC
