### ISSUE TITLE
meraki_syslog - Deploying same server 'roles' configuration results in 'TypeError: 'NoneType' object is not subscriptable'

### ISSUE THREAD

**Issue by KyleFryer-Sage** [CiscoDevNet/ansible-meraki#288] opened 2022-02-18 17:38 UTC
Judging by the traceback, it seems it is struggling during _generate_diff_, in instances where **identical** **roles** are re-deployed.

For example, the first attempt of the following input, works:
```
servers:
  - host: 10.20.30.40
    port: 1234
    roles:
      - Air Marshal events
      - Flows
      - URLs
      - Wireless Event log
```

But when attempting to deploy again, where the diff should find the configurations identical and thus deploy no changes, we find that:
`"module_stderr": "Traceback (most recent call last):\n  File \"/home/<user>/.ansible/tmp/ansible-tmp-1645205620.6296048-1211-154072736849440/AnsiballZ_meraki_syslog.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/<user>/.ansible/tmp/ansible-tmp-1645205620.6296048-1211-154072736849440/AnsiballZ_meraki_syslog.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/<user>/.ansible/tmp/ansible-tmp-1645205620.6296048-1211-154072736849440/AnsiballZ_meraki_syslog.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_syslog', init_globals=dict(_module_fqn='ansible_collections.cisco.meraki.plugins.modules.meraki_syslog', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_meraki_syslog_payload_cqd5ntqu/ansible_meraki_syslog_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_syslog.py\", line 260, in <module>\n  File \"/tmp/ansible_meraki_syslog_payload_cqd5ntqu/ansible_meraki_syslog_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_syslog.py\", line 245, in main\n  File \"/tmp/ansible_meraki_syslog_payload_cqd5ntqu/ansible_meraki_syslog_payload.zip/ansible_collections/cisco/meraki/plugins/module_utils/network/meraki/meraki.py\", line 205, in generate_diff\nTypeError: 'NoneType' object is not subscriptable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}`

**Comment by kbreit** [comment] 2022-03-05 02:46
I'm looking into this tonight and was able to reproduce it. What's interesting is it worked fine if I had a single item in the role list but if I increased the length to two, it failed. Looking into this more.

**Comment by kbreit** [comment] 2022-03-05 03:23
@KyleFryer-Sage - Do you have the ability to test the code using PR #289?

**Comment by KyleFryer-Sage** [comment] 2022-03-07 17:50
Thanks for taking your time to look at this!

I tested with PR 289, and cleared my Ansible /tmp directory:
`commit e6055201bbdce93fcc90bc90a2057d5b6fdf0dc6 (HEAD, origin/bugfix/288-meraki_syslog-idempotency))`

```
git branch -a
* (HEAD detached at e605520)
  master
```

When I test multiple times against a wireless network with the following, checking idempotency, the following **works as expected**:
```
        servers:
          - host: 192.0.1.2
            port: 514
            roles:
              - Air Marshal events
              - Flows
              - URLs
```

When I test multiple times on a wireless network with the following, checking idempotency, the following **fails**:
```
        servers:
          - host: 192.0.1.2
            port: 514
            roles:
              - Air Marshal events
              - Flows
              - Wireless Event log
```

This also **fails:**:
```
 servers:
          - host: 192.0.1.2
            port: 514
            roles:
              - Air Marshal events
              - Flows
              - URLs
              - Wireless Event log
```

I then tested only with the 'Wireless Event log' role, and found that this **fails** idempotency and throws the error:
```
 servers:
          - host: 192.0.1.2
            port: 514
            roles:
              - Wireless Event log
```

The error:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/<user>/.ansible/tmp/ansible-tmp-1646673829.8508594-5374-51596038147163/AnsiballZ_meraki_syslog.py", line 107, in <module>
    _ansiballz_main()
  File "/home/<user>/.ansible/tmp/ansible-tmp-1646673829.8508594-5374-51596038147163/AnsiballZ_meraki_syslog.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/<user>/.ansible/tmp/ansible-tmp-1646673829.8508594-5374-51596038147163/AnsiballZ_meraki_syslog.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_syslog', init_globals=dict(_module_fqn='ansible_collections.cisco.meraki.plugins.modules.meraki_syslog', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_meraki_syslog_payload_8yoj21q0/ansible_meraki_syslog_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_syslog.py", line 294, in <module>
  File "/tmp/ansible_meraki_syslog_payload_8yoj21q0/ansible_meraki_syslog_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_syslog.py", line 279, in main
  File "/tmp/ansible_meraki_syslog_payload_8yoj21q0/ansible_meraki_syslog_payload.zip/ansible_collections/cisco/meraki/plugins/module_utils/network/meraki/meraki.py", line 205, in generate_diff
TypeError: 'NoneType' object is not subscriptable
failed: [localhost] (item={'net_name': '<TEST_LAB>', 'syslog_server': '192.0.1.2', 'syslog_port': '514', 'syslog_roles': 'Wireless Event log'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "net_name": "<TEST_LAB>",
        "syslog_port": "514",
        "syslog_roles": "Wireless Event log",
        "syslog_server": "192.0.1.2",
    },
```

After doing these tests, this looks like it could possibly just be an issue with that particular role **'Wireless Event log'** during the idempotent checks?

**Comment by kbreit** [comment] 2022-03-09 04:16
My current thought is it I would be weird if one role is the culprit here as they're "just" strings. I'm going to investigate why further to see what's going on. Thanks for the test cases.

Have you tested it on appliance or switch networks to see if those have similar problems?

**Comment by kbreit** [comment] 2022-03-09 12:19
@KyleFryer-Sage - The culprit seems to be related to case sensitivity. I'm specifying a list of acceptable roles in the playbook https://github.com/CiscoDevNet/ansible-meraki/blob/6c6f4676d188581aec6efae9b6b6d54aa95396b0/plugins/modules/meraki_syslog.py#L160 and Ansible treats those in a case-sensitive manner. Meraki on the other hand is case insensitive per documentation.

> A list of roles for the syslog server. Options (case-insensitive)...
> - https://github.com/CiscoDevNet/ansible-meraki/blob/master/plugins/modules/meraki_syslog.py#L160

My modules are forcing you to input a case sensitive value and Meraki isn't necessarily sending the same thing back so when it sees if `have` and `want` match it sees a difference. I'll need to rework how I'm defining and enforcing the options and normalize the comparison a little bit but it shouldn't be too bad to do.

**Comment by kbreit** [comment] 2022-03-11 03:00
@KyleFryer-Sage Please try again with the same branch.

**Comment by KyleFryer-Sage** [comment] 2022-03-11 12:13
That seems to have sorted it, ran it multiple times with the same cases as I previously tried above, and all working as expected; idempotency checks are successful and not throwing any errors. 

``` 
git log
commit e5fa4766415cb652983082804cf25cbc390c7f94 (HEAD, origin/bugfix/288-meraki_syslog-idempotency)
Author: Kevin Breit <kevin.breit@kevinbreit.net>
Date:   Thu Mar 10 21:00:03 2022 -0600 
```

Thanks again!

**Comment by kbreit** [comment] 2022-03-11 12:16
Thanks for the update. I'm trying to see if I can set the choices in the `arg_spec` to be case insensitive natively within Ansible. If I can, I'll make that update and merge.

**Comment by feisa** [comment] 2022-03-30 02:23
@kbreit looks like the issue is still present just tested

**Comment by kbreit** [comment] 2022-03-30 02:25
@feisa What is your playbook? I'm curious what's different. And what collection version are you using?

**Comment by feisa** [comment] 2022-03-30 02:41
Maybe me structure is wrong with 4 syslog servers 
 cisco.meraki          2.6.1  
 meraki_syslog:
    auth_key: "{{ meraki_api_key }}"
    state: present
    org_name: "{{ meraki_org.data[0].name }}"
    net_id: "{{ item.network_id }}"
    servers:
      - host: "10.3.15.11"
        port: 604
        roles:
          - Appliance event log
          - Security events
      - host: "10.5.15.11"
        port: 604
        roles:
          - Appliance event log
          - Security events
      - host: "10.9.15.11"
        port: 604
        roles:
          - Appliance event log
          - Security events
      - host: "10.5.250.12"
        port: 514
        roles:
          - Appliance event log
          - Security events

**Comment by kbreit** [comment] 2022-03-30 12:07
Thanks. I'll take a look in the near future. Hopefully Friday.

**Comment by kbreit** [comment] 2022-03-31 02:19
@feisa - Please paste the error you're getting as the integration test I added with your task seems to work. Also, please modify the module name to be `cisco.meraki.meraki_syslog` to ensure it's using the collection.

**Comment by oliverl-21** [comment] 2022-05-02 11:53
i receive the same error but on meraki_mx_vlan.
The diff check should recognise no change needs to be done and then errors with:
```yml
# task
  - name: set vlan 101 Clients
    cisco.meraki.meraki_mx_vlan:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ item.site_name }}"
      state: present
      vlan_id: 101
      name: Clients
      subnet: "10.{{ item.site_octet }}.101.0/27"
      appliance_ip: 10.{{ item.site_octet }}.101.1
    loop: "{{ site }}"
    loop_control:
      label: "{{ item.site_name }}"
```

```
The full traceback is:
Traceback (most recent call last):
  File "/Users/oliver/.ansible/tmp/ansible-tmp-1651492136.3267891-62421-102830058445798/AnsiballZ_meraki_mx_vlan.py", line 107, in <module>
    _ansiballz_main()
  File "/Users/oliver/.ansible/tmp/ansible-tmp-1651492136.3267891-62421-102830058445798/AnsiballZ_meraki_mx_vlan.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/oliver/.ansible/tmp/ansible-tmp-1651492136.3267891-62421-102830058445798/AnsiballZ_meraki_mx_vlan.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_mx_vlan', init_globals=dict(_module_fqn='ansible_collections.cisco.meraki.plugins.modules.meraki_mx_vlan', _modlib_path=modlib_path),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/6g/cclk58y94dz5xwsmy4l28xq00000gn/T/ansible_cisco.meraki.meraki_mx_vlan_payload_0eelm70n/ansible_cisco.meraki.meraki_mx_vlan_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_vlan.py", line 585, in <module>
  File "/var/folders/6g/cclk58y94dz5xwsmy4l28xq00000gn/T/ansible_cisco.meraki.meraki_mx_vlan_payload_0eelm70n/ansible_cisco.meraki.meraki_mx_vlan_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_vlan.py", line 562, in main
  File "/var/folders/6g/cclk58y94dz5xwsmy4l28xq00000gn/T/ansible_cisco.meraki.meraki_mx_vlan_payload_0eelm70n/ansible_cisco.meraki.meraki_mx_vlan_payload.zip/ansible_collections/cisco/meraki/plugins/module_utils/network/meraki/meraki.py", line 205, in generate_diff
TypeError: 'NoneType' object is not subscriptable
failed: [localhost] (item=site 1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "site_address": "Banana, Kiribati",
        "site_name": "site 1",
        "site_octet": 12
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/oliver/.ansible/tmp/ansible-tmp-1651492136.3267891-62421-102830058445798/AnsiballZ_meraki_mx_vlan.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/oliver/.ansible/tmp/ansible-tmp-1651492136.3267891-62421-102830058445798/AnsiballZ_meraki_mx_vlan.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/oliver/.ansible/tmp/ansible-tmp-1651492136.3267891-62421-102830058445798/AnsiballZ_meraki_mx_vlan.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_mx_vlan', init_globals=dict(_module_fqn='ansible_collections.cisco.meraki.plugins.modules.meraki_mx_vlan', _modlib_path=modlib_path),\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/6g/cclk58y94dz5xwsmy4l28xq00000gn/T/ansible_cisco.meraki.meraki_mx_vlan_payload_0eelm70n/ansible_cisco.meraki.meraki_mx_vlan_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_vlan.py\", line 585, in <module>\n  File \"/var/folders/6g/cclk58y94dz5xwsmy4l28xq00000gn/T/ansible_cisco.meraki.meraki_mx_vlan_payload_0eelm70n/ansible_cisco.meraki.meraki_mx_vlan_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_vlan.py\", line 562, in main\n  File \"/var/folders/6g/cclk58y94dz5xwsmy4l28xq00000gn/T/ansible_cisco.meraki.meraki_mx_vlan_payload_0eelm70n/ansible_cisco.meraki.meraki_mx_vlan_payload.zip/ansible_collections/cisco/meraki/plugins/module_utils/network/meraki/meraki.py\", line 205, in generate_diff\nTypeError: 'NoneType' object is not subscriptable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by kbreit** [comment] 2022-05-11 12:23
@oliverl-21 Thanks for reporting this. I'm going to create a new issue for this and tag you in it.

**Comment by kbreit** [comment] 2022-06-30 11:59
I'm closing this issue as I believe it's resolved. If it's not, please create a new issue and I'll addess it there.

**Closed by kbreit** 2022-06-30 11:59 UTC
